logging:
  file: logs/furnace-it.log
spring:
  jmx:
    port: 49004
  data:
    elasticsearch:
      repositories:
        enabled: false
server:
  port: 48004
  
infrastructure:
  environment-name: it
  amqp-camel-component: stub
  amqp-server: nowhere:1
  amqp-ticks-exchange: turbine.it.market.ticks
  amqp-ticks-queue: turbine.it.queue.ticks
  elasticsearch-index-for-ticks: turbine-ticks
  elasticsearch-index-for-indicators: turbine-indicators
  elasticsearch-index-for-strategies: turbine-strategies
  elasticsearch-type-for-ticks: turbine-tick
  elasticsearch-type-for-indicators: turbine-indicator
  elasticsearch-type-for-strategies: turbine-strategy
  
