infrastructure:
  environment-name: test1
  amqp-ticks: rabbitmq://localhost:5672/turbine.test1.market.ticks?exchangeType=topic&queue=turbine.test1.queue.ticks
  amqp-stocks: rabbitmq://localhost:5672/turbine.test1.market.stocks?exchangeType=topic&queue=turbine.test1.queue.indicators
  elasticsearch-host: localhost
  elasticsearch-port: 9300
  websocket-ticks: /topic/ticks
  websocket-stocks: /topic/stocks
  
spring:
  data:
    elasticsearch:
      cluster-nodes: localhost:9300
      repositories:
        enabled: true