infrastructure:
  environment-name: test1
  amqp-ticks: rabbitmq://localhost:5672/turbine.test1.exchange.ticks?exchangeType=topic&queue=turbine.test1.queue.ticks
  elasticsearch-host: localhost
  elasticsearch-port: 9300
  websocket-ticks: /topic/ticks
  
spring:
  data:
    elasticsearch:
      cluster-nodes: localhost:9300
      repositories:
        enabled: true